### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by jonnor** [fpaissan/tinyCLAP#1]
Hi @fpaissan - thanks for great presentation and interesting talk at TinyML EMEA. And thank you for publishing the training codes, so others can easily build on your work.

I notice that there is no licensing information available. Under what license is the code (and the pretrained weights)? If the intent is to be open source, then it makes sense to select one of the standard/common open source licenses. Preferably by including the license text as a file in the git repo - and also marking it in Github (it will usually autodetect based on a LICENSE file, I think).

**Comment by fpaissan** [comment]
Hey, @jonnor, thanks!
Indeed, I meant to do that before releasing the code but ultimately forgot. I'll create a PR for that now.

My intent is to release both code and pretrained weights publicly under an Apache license. Be mindful, however, that we use the [MSFT weights](https://huggingface.co/microsoft/msclap) for the BERT  encoder. This might imply that their licensing applies somehow to that portion of the weights (?).

**Comment by fpaissan** [comment]
Oops. The issue got closed when merging the PR. Feel free to re-open if you have further comments! :)

**Comment by jonnor** [comment]
Thanks for the super quick response on adding the license. Regarding the BERT encoder, I just recommend mentioning it briefly in a Licensing section in the README. Who knows exactly how the licensing works out, but then people are informed and can judge for themselves. Considering that TinyCLAP is distilled to match a pretrained network, perhaps also mention that license (if you consider it relevant)?

**Comment by fpaissan** [comment]
Indeed, that would be the best approach. This way, everyone can decide for themselves what is best.

I added a licensing paragraph to the README in #3 

Feel free to close the issue if you don't have more suggestions.

**Comment by jonnor** [comment]
Super, I think that is great! :) Thanks
